---
  - name: "install packages"
    apt:
      name: ['zsh', 'emacs', 'tmux']
      state: present
    become: true

  - name: "installing .emacs.d configurations"
    synchronize:
      src: "{{playbook_dir}}/.emacs.d"
      dest: ~/

  - name: "installing .emacs.d configurations for root"
    synchronize:
      src: "{{playbook_dir}}/.emacs.d"
      dest: /root/
    become: true

  - name: "Delete previous oh-my-zsh installation"
    file:
      path: ~/.oh-my-zsh
      state: absent

  - name: "Download and install oh-my-zsh"
    shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: "Install zsh-syntax-highlighting from repo"
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: "Install zsh-autosuggestions from repo"
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

  - name: "Download zsh theme"
    synchronize:
      src: "{{playbook_dir}}/minimal.zsh-theme"
      dest: ~/.oh-my-zsh/custom/themes/minimal.zsh-theme

  - name: "Install zsh-autosuggestions from repo"
    git:
      repo: "https://github.com/tmux-plugins/tpm"
      dest: ~/.tmux/plugins/tpm

  - name: "Installing .tmux.conf"
    synchronize:
      src: "{{playbook_dir}}/.tmux.conf"
      dest: ~/.tmux.conf

  - name: "Installing .zshrc"
    synchronize:
      src: "{{playbook_dir}}/.zshrc"
      dest: ~/.zshrc

  - name: "Installing authorized_keys for luca.bodini"
    synchronize:
      src: "{{playbook_dir}}/.ssh/authorized_keys"
      dest: ~/.ssh/authorized_keys
      
 
