---
  - name: "install packages"
    openbsd_pkg:
      name: ['zsh', 'emacs-26.3-no_x11']
      state: present
    become: true

  - name: "Delete previous oh-my-zsh installation"
    file:
      path: ~/.oh-my-zsh
      state: absent

  - name: "Download and install oh-my-zsh"
    shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: "Install zsh-syntax-highlighting from repo"
    git:
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlightingx

  - name: "Install zsh-autosuggestions from repo"
    git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

  - name: "Download zsh theme"
    get_url:
      url: https://raw.githubusercontent.com/lucabodd/server-dotfiles/master/minimal.zsh-theme
      dest: ~/.oh-my-zsh/custom/themes/minimal.zsh-theme

  - name: "Install zsh-autosuggestions from repo"
    git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: ~/.tmux/plugins/tpm

  - name: "Download .tmux.conf"
    get_url:
      url: https://raw.githubusercontent.com/lucabodd/server-dotfiles/master/.tmux.conf.obsd
      dest: ~/.tmux.conf

  - name: "Download .zshrc"
    get_url:
      url: https://raw.githubusercontent.com/lucabodd/server-dotfiles/master/.zshrc
      dest: ~/.zshrc

  - name: "Download authorized_keys for luca.bodini"
    get_url:
      url: https://raw.githubusercontent.com/lucabodd/server-dotfiles/master/.ssh/authorized_keys
      dest: ~/.ssh/authorized_keys
      
  - name: "Download authorized_keys for root"
    shell: curl https://raw.githubusercontent.com/lucabodd/server-dotfiles/master/.ssh/authorized_keys >> ~/.ssh/authorized_keys
    become: true
