---
  - name: "install packages"
    openbsd_pkg:
      name: ['zsh', 'emacs-26.3-no_x11']
      state: present
    become: true

  - name: "installing .emacs.d configurations"
    copy:
      src: "{{playbook_dir}}/.emacs.d"
      dest: ~/
      force: yes
      directory_mode: yes

  - name: "Delete previous oh-my-zsh installation"
    file:
      path: ~/.oh-my-zsh
      state: absent

  - name: "Download and install oh-my-zsh"
    shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: "Install zsh-syntax-highlighting from repo"
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: "Install zsh-autosuggestions from repo"
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

  - name: "Download zsh theme"
    copy:
      src: "{{playbook_dir}}/minimal.zsh-theme"
      dest: ~/.oh-my-zsh/custom/themes/minimal.zsh-theme
      force: yes

  - name: "Install zsh-autosuggestions from repo"
    git:
      repo: "https://github.com/tmux-plugins/tpm"
      dest: ~/.tmux/plugins/tpm

  - name: "Installing .tmux.conf"
    copy:
      src: "{{playbook_dir}}/.tmux.conf.obsd"
      dest: ~/.tmux.conf
      force: yes

  - name: "Installing .zshrc"
    copy:
      src: "{{playbook_dir}}/.zshrc"
      dest: ~/.zshrc
      force: yes

  - name: "Installing authorized_keys for luca.bodini"
    copy:
      src: "{{playbook_dir}}/.ssh/authorized_keys"
      dest: ~/.ssh/authorized_keys

  - name: "Changing default shell to zsh"
    shell: chsh -s $(which zsh)
      
 